"""
Natural-language Q&A over the applications table. Read-only: the LLM only
extracts search filters from the question, it never writes to the DB or
triggers other actions. The answer text is built deterministically from the
matched rows rather than generated by the LLM.
"""

import re
from datetime import date, timedelta

from sqlalchemy.orm import Session

from src.services import application_service, dashboard_service
from src.services.llm_client import LLMClient, extract_json, get_llm_client

MAX_RESULTS_FOR_CONTEXT = 20


def _today() -> date:
    return date.today()


def _first_day_last_month(today: date) -> date:
    first_of_this_month = today.replace(day=1)
    last_month_end = first_of_this_month - timedelta(days=1)
    return last_month_end.replace(day=1)


def _last_day_last_month(today: date) -> date:
    first_of_this_month = today.replace(day=1)
    return first_of_this_month - timedelta(days=1)

_FILTER_KEYS = (
    "planning_authority",
    "planning_status_current",
    "application_type",
    "date_received_from",
    "date_received_to",
    "q",
)


def _extraction_prompt(db: Session) -> str:
    authorities = dashboard_service.get_distinct_authorities(db)
    statuses = sorted(r["label"] for r in dashboard_service.get_status_breakdown(db) if r["label"])
    types = sorted(r["label"] for r in dashboard_service.get_type_breakdown(db) if r["label"])
    return (
        f"Today's date is {_today().isoformat()}. Resolve relative date phrases "
        "like 'last month', 'this year', or 'last week' against this date, not "
        "your training data.\n\n"
        "You translate a user's question about Irish planning applications into a JSON "
        "filter object. Reply with ONLY the JSON object, no other text.\n\n"
        "Allowed keys (omit any key you can't confidently determine):\n"
        '  "planning_authority": one of ' + str(authorities) + "\n"
        '  "planning_status_current": one of ' + str(statuses) + "\n"
        '  "application_type": one of ' + str(types) + "\n"
        '  "date_received_from": "YYYY-MM-DD"\n'
        '  "date_received_to": "YYYY-MM-DD"\n'
        '  "q": one or more space-separated keywords to search applicant/address/description '
        '(e.g. a place name); every keyword must match, so only include words that should ALL '
        "be present\n\n"
        "If the question mentions a place name (e.g. a town or area), put it ONLY in \"q\" "
        "-- do not also guess \"planning_authority\" from the place name, even if you know "
        "which council the place falls under. Only set \"planning_authority\" if the "
        "question explicitly names a council. "
        "Only set \"application_type\" if the question explicitly names a type (e.g. "
        "\"permission\", \"retention\") -- never guess a type just because the question "
        "mentions an application number, applicant name, or address; omit the key if the "
        "question doesn't say what type it is. "
        "Only set \"planning_status_current\" if the question explicitly names a status "
        "(e.g. \"granted\", \"refused\", \"withdrawn\") -- never guess a status, and never "
        "use \"unknown\" or any other word not in the allowed list above, just because the "
        "question asks what the status IS; asking for the status means the field should "
        "be omitted, not guessed. "
        "The question may use an everyday synonym instead of the exact allowed status word "
        "-- always map it to the matching allowed value from the list above, never put the "
        "synonym itself into \"planning_status_current\" or into \"q\". Common synonyms: "
        "\"rejected\", \"denied\", or \"declined\" all mean \"Refused\"; \"approved\" means "
        "\"Granted\"; \"pending\" or \"in progress\" means \"Received\". "
        "If the question includes an application reference number (e.g. \"26/20\" or "
        "\"2661040\"), always include that exact number as one of the keywords in \"q\", "
        "in addition to any applicant name also mentioned. "
        "Do not put dates or date phrases inside \"q\" -- always express any time range "
        "using \"date_received_from\" / \"date_received_to\" instead, and never combine "
        "a place name and a date into one \"q\" string. "
        "If a field can't be determined, omit the key entirely rather than guessing.\n\n"
        "Every date value you output must be a real, fully computed YYYY-MM-DD date "
        "-- never a placeholder or description like \"<first day of last month>\".\n\n"
        "Examples:\n"
        f'  Question: "What\'s new in Tuam for last month"\n'
        '  Reply: {"q": "Tuam", "date_received_from": "' + _first_day_last_month(_today()).isoformat() +
        '", "date_received_to": "' + _last_day_last_month(_today()).isoformat() + '"}\n'
        '  Question: "What\'s the status of application 26/20 for Mr Kevin Burke"\n'
        '  Reply: {"q": "26/20 Kevin Burke"}\n'
        '  Question: "Show me the rejected applications from last month"\n'
        '  Reply: {"planning_status_current": "Refused", "date_received_from": "'
        + _first_day_last_month(_today()).isoformat() + '", "date_received_to": "'
        + _last_day_last_month(_today()).isoformat() + '"}\n'
        '  Question: "Which applications were approved in Oranmore?"\n'
        '  Reply: {"planning_status_current": "Granted", "q": "Oranmore"}\n'
    )


def _extract_filters(client: LLMClient, db: Session, question: str) -> dict:
    system = _extraction_prompt(db)
    reply = client.chat(system, question)
    parsed = extract_json(reply)
    if not parsed:
        return {}
    filters = {k: v for k, v in parsed.items() if k in _FILTER_KEYS and v}

    enum_filters = {
        "planning_authority": dashboard_service.get_distinct_authorities(db),
        "planning_status_current": [
            r["label"] for r in dashboard_service.get_status_breakdown(db) if r["label"]
        ],
        "application_type": [
            r["label"] for r in dashboard_service.get_type_breakdown(db) if r["label"]
        ],
    }
    for key, allowed_values in enum_filters.items():
        if key in filters and filters[key] not in set(allowed_values):
            del filters[key]

    for key in ("date_received_from", "date_received_to"):
        if key in filters and not _is_valid_iso_date(filters[key]):
            del filters[key]

    # A question naming a specific application ref (e.g. "26/20") is already
    # precisely scoped by that ref -- small models tend to guess an unrelated
    # status in this case, so don't trust a status guess when a ref is present.
    if "planning_status_current" in filters and _contains_application_ref(filters.get("q", "")):
        del filters["planning_status_current"]

    # The prompt tells the model never to guess planning_authority from a place
    # name alone, but small models do it anyway (e.g. "Tuam" -> "Galway City
    # Council", which is wrong and silently drops ~99% of real matches). Only
    # trust the guess if the question text itself names the authority.
    if "planning_authority" in filters and not _mentions_authority(question, filters["planning_authority"]):
        del filters["planning_authority"]

    return filters


def _mentions_authority(question: str, authority: str) -> bool:
    question_lower = question.lower()
    if authority.lower() in question_lower:
        return True
    # Accept "Galway city council" without requiring "county"/"city" to match
    # exactly, but still require the place qualifier, not just the bare word
    # "galway" (which appears in nearly every question in this dataset).
    for qualifier in ("city council", "county council"):
        if qualifier in authority.lower() and qualifier in question_lower:
            return True
    return False


_APPLICATION_REF_PATTERN = re.compile(r"\d+/\d+")


def _contains_application_ref(q: str) -> bool:
    return bool(_APPLICATION_REF_PATTERN.search(q))


def _is_valid_iso_date(value: str) -> bool:
    try:
        date.fromisoformat(value)
        return True
    except (TypeError, ValueError):
        return False


_OUT_OF_COVERAGE_MESSAGE = (
    "No applications matched your question. This pilot currently covers Galway "
    "City and County only — coverage of other counties is in progress and will "
    "be added soon."
)

_NO_MATCH_FOR_FILTERS_MESSAGE = (
    "No applications matched that specific combination of filters. Try removing "
    "the status or date part of your question to see everything for that place."
)


def _summarize(rows: list, total: int, q_only_had_matches: bool | None) -> str:
    # Deterministic on purpose: small local models were observed answering from
    # general trivia about a place/company name (e.g. "Dublin") instead of the
    # rows, so the answer text must not depend on an LLM call at all.
    if total == 0:
        # q_only_had_matches is False only when a place/keyword was given and it
        # matched nothing at all, regardless of other filters -- that's the true
        # "outside pilot coverage" case. Any other zero-result case (no "q" at
        # all, or "q" matched but other filters narrowed it out) means the
        # filters were just too narrow, not that the place is unsupported.
        if q_only_had_matches is False:
            return _OUT_OF_COVERAGE_MESSAGE
        return _NO_MATCH_FOR_FILTERS_MESSAGE

    shown = min(total, MAX_RESULTS_FOR_CONTEXT)
    example_refs = ", ".join(app.application_ref for app in rows[:5])
    if total > shown:
        return (
            f"Found {total} matching application(s); showing the first {shown} "
            f"below, e.g. {example_refs}."
        )
    return f"Found {total} matching application(s), listed below, e.g. {example_refs}."


_UNAVAILABLE_MESSAGE = (
    "The AI assistant is temporarily unavailable, so your question couldn't be "
    "answered. Please try again in a moment."
)


def answer_question(db: Session, question: str, client: LLMClient | None = None) -> dict:
    """Returns {"answer": str, "filters": dict, "applications": list, "total": int}."""
    client = client or get_llm_client()

    try:
        filters = _extract_filters(client, db, question)
    except Exception:
        return {
            "answer": _UNAVAILABLE_MESSAGE,
            "filters": {},
            "applications": [],
            "total": 0,
        }

    full_filters = {k: filters.get(k) for k in _FILTER_KEYS}
    rows, total = application_service.search(db, full_filters, page=1, page_size=MAX_RESULTS_FOR_CONTEXT)

    q_only_had_matches = None
    if total == 0 and filters.get("q"):
        other_filters_present = any(filters.get(k) for k in _FILTER_KEYS if k != "q")
        if other_filters_present:
            _, q_only_total = application_service.search(
                db, {"q": filters["q"]}, page=1, page_size=1
            )
            q_only_had_matches = q_only_total > 0
        else:
            q_only_had_matches = False

    answer = _summarize(rows, total, q_only_had_matches)

    return {
        "answer": answer,
        "filters": filters,
        "applications": rows,
        "total": total,
    }
