"""create applications and events

Revision ID: 0001
Revises:
Create Date: 2026-06-27 21:24:29.624467

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('planning_authority', sa.String(), nullable=False),
    sa.Column('source_entity', sa.String(), nullable=False),
    sa.Column('application_ref', sa.String(), nullable=False),
    sa.Column('application_ref_type', sa.String(), nullable=True),
    sa.Column('applicant_name', sa.String(), nullable=False),
    sa.Column('site_address', sa.String(), nullable=True),
    sa.Column('site_locality', sa.String(), nullable=True),
    sa.Column('site_county', sa.String(), nullable=True),
    sa.Column('site_geometry', geoalchemy2.types.Geometry(srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('development_description', sa.String(), nullable=False),
    sa.Column('application_type', sa.String(), nullable=False),
    sa.Column('planning_status_current', sa.String(), nullable=False),
    sa.Column('status_event_type', sa.String(), nullable=True),
    sa.Column('date_received', sa.Date(), nullable=False),
    sa.Column('decision_due_date', sa.Date(), nullable=True),
    sa.Column('decision_date', sa.Date(), nullable=True),
    sa.Column('further_information_flag', sa.Boolean(), nullable=False),
    sa.Column('protected_structure_flag', sa.Boolean(), nullable=False),
    sa.Column('eia_eis_flag', sa.Boolean(), nullable=False),
    sa.Column('other_regulatory_flags', sa.JSON(), nullable=False),
    sa.Column('official_detail_url', sa.String(), nullable=True),
    sa.Column('official_documents_url', sa.String(), nullable=True),
    sa.Column('source_system', sa.String(), nullable=False),
    sa.Column('source_file', sa.String(), nullable=False),
    sa.Column('source_ingested_at', sa.DateTime(), nullable=False),
    sa.Column('raw_payload_json', sa.JSON(), nullable=False),
    sa.Column('market_entity', sa.String(), nullable=True),
    sa.Column('commuter_belt_flag', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('planning_authority', 'application_ref', name='uq_application_natural_key')
    )
    # NOTE: a GIST spatial index on applications.site_geometry is created
    # automatically by GeoAlchemy2's after_create DDL event (Geometry
    # columns default to spatial_index=True), so no explicit op.create_index
    # call is needed here — adding one causes a DuplicateTable error.
    op.create_table('application_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('application_ref', sa.String(), nullable=False),
    sa.Column('planning_authority', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('source_file', sa.String(), nullable=False),
    sa.Column('raw_payload_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('application_events')
    op.drop_table('applications')
    # ### end Alembic commands ###
